



















// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `Security_ConnectionString`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=.;Initial Catalog=TeamRights; UID=sa;PWD=123456;MultipleActiveResultSets=True`



using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PetaPoco;

namespace Security_ConnectionString
{
	public partial class Security_ConnectionStringDB : Database
	{
		public Security_ConnectionStringDB() 
			: base("Security_ConnectionString")
		{
			CommonConstruct();
		}

		public Security_ConnectionStringDB(string connectionStringName) 
			: base(connectionStringName)
		{
			CommonConstruct();
		}
		
		partial void CommonConstruct();
		
		public interface IFactory
		{
			Security_ConnectionStringDB GetInstance();
		}
		
		public static IFactory Factory { get; set; }
        public static Security_ConnectionStringDB GetInstance()
        {
			if (_instance!=null)
				return _instance;
				
			if (Factory!=null)
				return Factory.GetInstance();
			else
				return new Security_ConnectionStringDB();
        }

		[ThreadStatic] static Security_ConnectionStringDB _instance;
		
		public override void OnBeginTransaction()
		{
			if (_instance==null)
				_instance=this;
		}
		
		public override void OnEndTransaction()
		{
			if (_instance==this)
				_instance=null;
		}
        

		public class Record<T> where T:new()
		{
			public static Security_ConnectionStringDB repo { get { return Security_ConnectionStringDB.GetInstance(); } }
			public bool IsNew() { return repo.IsNew(this); }
			public void Save() { repo.Save(this); }
			public object Insert() { return repo.Insert(this); }
			public int Update() { return repo.Update(this); }
			public int Delete() { return repo.Delete(this); }
			public static int Update(string sql, params object[] args) { return repo.Delete<T>(sql, args); }
			public static int Update(Sql sql) { return repo.Delete<T>(sql); }
			public static int Delete(string sql, params object[] args) { return repo.Delete<T>(sql, args); }
			public static int Delete(Sql sql) { return repo.Delete<T>(sql); }
			public static int Delete(object primaryKey) { return repo.Delete<T>(primaryKey); }
			public static bool Exists(object primaryKey) { return repo.Exists<T>(primaryKey); }
			public static T SingleOrDefault(object primaryKey) { return repo.SingleOrDefault<T>(primaryKey); }
			public static T SingleOrDefault(string sql, params object[] args) { return repo.SingleOrDefault<T>(sql, args); }
			public static T SingleOrDefault(Sql sql) { return repo.SingleOrDefault<T>(sql); }
			public static T FirstOrDefault(string sql, params object[] args) { return repo.FirstOrDefault<T>(sql, args); }
			public static T FirstOrDefault(Sql sql) { return repo.FirstOrDefault<T>(sql); }
			public static T Single(object primaryKey) { return repo.Single<T>(primaryKey); }
			public static T Single(string sql, params object[] args) { return repo.Single<T>(sql, args); }
			public static T Single(Sql sql) { return repo.Single<T>(sql); }
			public static T First(string sql, params object[] args) { return repo.First<T>(sql, args); }
			public static T First(Sql sql) { return repo.First<T>(sql); }
			public static List<T> Fetch(string sql, params object[] args) { return repo.Fetch<T>(sql, args); }
			public static List<T> Fetch(Sql sql) { return repo.Fetch<T>(sql); }
			public static List<T> Fetch(long page, long itemsPerPage, string sql, params object[] args) { return repo.Fetch<T>(page, itemsPerPage, sql, args); }
			public static List<T> Fetch(long page, long itemsPerPage, Sql sql) { return repo.Fetch<T>(page, itemsPerPage, sql); }
			public static Page<T> Page(long page, long itemsPerPage, string sql, params object[] args) { return repo.Page<T>(page, itemsPerPage, sql, args); }
			public static Page<T> Page(long page, long itemsPerPage, Sql sql) { return repo.Page<T>(page, itemsPerPage, sql); }
			public static IEnumerable<T> Query(string sql, params object[] args) { return repo.Query<T>(sql, args); }
			public static IEnumerable<T> Query(Sql sql) { return repo.Query<T>(sql); }
		}

	}
	


    
	[TableName("OU_Role")]

	[PrimaryKey("OU_ID")]

	[ExplicitColumns]
    public partial class OU_Role : Security_ConnectionStringDB.Record<OU_Role>  
    {

        [Column] public int OU_ID { get; set; }

        [Column] public int Role_ID { get; set; }

        [Column] public int TopOUID { get; set; }

	}


    
	[TableName("OU_User")]

	[PrimaryKey("OU_ID")]

	[ExplicitColumns]
    public partial class OU_User : Security_ConnectionStringDB.Record<OU_User>  
    {

        [Column] public int User_ID { get; set; }

        [Column] public int OU_ID { get; set; }

	}


    
	[TableName("Role")]

	[PrimaryKey("ID")]

	[ExplicitColumns]
    public partial class Role : Security_ConnectionStringDB.Record<Role>  
    {

        [Column] public int ID { get; set; }

        [Column] public string Name { get; set; }

        [Column] public string Note { get; set; }

	}


    
	[TableName("Role_Function")]

	[PrimaryKey("Function_ID")]

	[ExplicitColumns]
    public partial class Role_Function : Security_ConnectionStringDB.Record<Role_Function>  
    {

        [Column] public int Role_ID { get; set; }

        [Column] public int Function_ID { get; set; }

	}


    
	[TableName("SystemAuthorize")]

	[PrimaryKey("ID")]

	[ExplicitColumns]
    public partial class SystemAuthorize : Security_ConnectionStringDB.Record<SystemAuthorize>  
    {

        [Column] public int ID { get; set; }

        [Column] public string SystemType_OID { get; set; }

        [Column] public string Content { get; set; }

	}


    
	[TableName("SystemType")]

	[PrimaryKey("OID")]

	[ExplicitColumns]
    public partial class SystemType : Security_ConnectionStringDB.Record<SystemType>  
    {

        [Column] public string OID { get; set; }

        [Column] public string Name { get; set; }

        [Column] public string CustomID { get; set; }

        [Column] public string Authorize { get; set; }

        [Column] public string Note { get; set; }

	}


    
	[TableName("User_Role")]

	[PrimaryKey("Role_ID")]

	[ExplicitColumns]
    public partial class User_Role : Security_ConnectionStringDB.Record<User_Role>  
    {

        [Column] public int User_ID { get; set; }

        [Column] public int Role_ID { get; set; }

        [Column] public int TopOUID { get; set; }

	}


    
	[TableName("Users")]

	[PrimaryKey("ID")]

	[ExplicitColumns]
    public partial class Operator : Security_ConnectionStringDB.Record<Operator>  
    {

        [Column] public int ID { get; set; }

        [Column] public int? PID { get; set; }

        [Column] public string Name { get; set; }

        [Column] public string Password { get; set; }

        [Column] public string FullName { get; set; }

        [Column] public bool? IsExpire { get; set; }

        [Column] public string Title { get; set; }

        [Column] public string IdentityCard { get; set; }

        [Column] public string MobilePhone { get; set; }

        [Column] public string OfficePhone { get; set; }

        [Column] public string HomePhone { get; set; }

        [Column] public string Email { get; set; }

        [Column] public string Address { get; set; }

        [Column] public string CustomField { get; set; }

        [Column] public int TopOUID { get; set; }

        [Column] public string Remark { get; set; }

	}


    
	[TableName("Functions")]

	[PrimaryKey("ID")]

	[ExplicitColumns]
    public partial class Function : Security_ConnectionStringDB.Record<Function>  
    {

        [Column] public int ID { get; set; }

        [Column] public int PID { get; set; }

        [Column] public string Name { get; set; }

        [Column] public string ControlID { get; set; }

        [Column] public string SystemType_ID { get; set; }

        [Column] public string Path { get; set; }

        [Column] public int? FunctionType { get; set; }

        [Column] public int? Sort { get; set; }

        [Column] public string ImageIndex { get; set; }

        [Column] public bool? IsEnabled { get; set; }

        [Column] public bool? IsInMenu { get; set; }

	}


    
	[TableName("OU")]

	[PrimaryKey("ID")]

	[ExplicitColumns]
    public partial class OU : Security_ConnectionStringDB.Record<OU>  
    {

        [Column] public int ID { get; set; }

        [Column] public int PID { get; set; }

        [Column] public string Name { get; set; }

        [Column] public string Address { get; set; }

        [Column] public string Note { get; set; }

        [Column] public bool Position { get; set; }

        [Column] public int OUOrder { get; set; }

        [Column] public string Path { get; set; }

	}


}

